. ~/devel/epics/env.sh
export EPICS_CA_MAX_ARRAY_BYTES=65536
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST="127.0.0.1"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$EPICS_BASE/lib/linux-x86_64/
